### ISSUE TITLE
Difficulty in understanding IonNIPT

### ISSUE THREAD

**Issue by GreeshmaThulasi** [AllanSSX/IonNIPT#2]
Hi,
I tried to do the IonNIPT. Is it possible with sinle-end sequenced BAM files?
But I am not clear about the workflow.
I cloned the directory by `git clone --recursive https://github.com/AllanSSX/IonNIPT.git` 
I am not clear that what to edit at the sanefalcon, defrag and IonNIPT.py files. So I couldn't do further. 
Could you please mind to let me know the working of this plugin.

Hoping to hear from you.

**Comment by alexcorm** [comment]
Hi,
Yes, it works either with paired and single data.
After the clone, you need to update IonNIPT.py and predict.sh (in Sanefalcon folder). In IonNIPT.py you need to update theses lines:
- line 37 you need to indicate the path the our sanefalcon model
- line 40 the scaling factor value obtain with Defrag
- line 109 and 113 the number of thread allow (for the parallelization)

And in predict.sh.
- line 2 give the full path to predict.py

An important point. For running IonNIPT, you need to first train Wisecondor, Defrag and Sanefalcon.

**Comment by GreeshmaThulasi** [comment]
Thank you so much for the reply.
I will try accordingly.
