### ISSUE TITLE
Is it able to identify Sex chromosomal aneuploidies?

### ISSUE THREAD

**Issue by GreeshmaThulasi** [AllanSSX/IonNIPT#3]
Hi,
Is it able to pick-up sex chromosomal aneuploidy?

**Comment by alexcorm** [comment]
Hi,
Sexual chromosomes are  not  evaluated  by  WISECONDOR so sex aneuploidy couldn’t  be  detected.

**Comment by GreeshmaThulasi** [comment]
Ok. Thanks for the reply.
